name:                page-builder
version:             0.1.0.0
github:              "DKurilo/page-builder"
license:             BSD3
author:              "Dima Kurilo"
maintainer:          "dkurilo@gmail.com"
copyright:           "Dima Kurilo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DKurilo/page-builder#readme>

dependencies:
- base >= 4.7 && < 5
- hw-kafka-client >= 3.1.2 && < 3.2
- stm >= 2.5 && < 2.6
- containers >= 0.6.2 && < 0.7
- text >= 1.2.2.1 && < 1.3
- bytestring >= 0.10.10 && < 0.11
- word8 >= 0.1.3 && < 0.2
- uuid >= 1.3.13 && < 1.4

library:
  source-dirs: src

executables:
  page-builder:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - page-builder

tests:
  page-builder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - page-builder
